CadeMeuMedico/Models/cidades.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeMeuMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cidades
    {
        public cidades()
        {
            this.medicos = new HashSet<medicos>();
        }
    
        public int IDCidade { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<medicos> medicos { get; set; }
    }
}

CadeMeuMedico/Controllers/CidadesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CadeMeuMedico.Models;
using System.Data;

namespace CadeMeuMedico.Controllers
{
    public class CidadesController : BaseController
    {
        //
        // GET: /Cidades/
        private cademeumedicoEntities db = new cademeumedicoEntities();

        public ActionResult ListaCidades()
        {
            var cidade = db.cidades.ToList(); // // SELECT
            return View(cidade);
        }


        // // INSERT
        public ActionResult Adicionar() //Mostra o formulario para preenchimento
        {
            return View();
        }

        [HttpPost]
        public ActionResult Adicionar(cidades cidade)
        {
            if (ModelState.IsValid)
            {
                db.cidades.Add(cidade);
                db.SaveChanges();
                return RedirectToAction("ListaCidades");
            }
            return View(cidade);
        }

        // // UPDATE
        public ActionResult Editar(long id)
        {
            cidades cidade = db.cidades.Find(id); //Retorna a cidade de acordo com o ID

            return View(cidade);
        }

        [HttpPost]
        public ActionResult Editar(cidades cidade)
        {
            if (ModelState.IsValid) //Verificando se o modelo é valido
            {
                db.Entry(cidade).State = EntityState.Modified; //Acessando o campo e Modificando
                db.SaveChanges();
                return RedirectToAction("ListaCidades");
            }

            return View(cidade);
        }

        // // DELETE
        public ActionResult Excluir(long id)
        {
            cidades cidade = db.cidades.Find(id);
            if (cidade != null)
            {
                db.cidades.Remove(cidade);
                db.SaveChanges();
                return RedirectToAction("ListaCidades");
            }
            return View(cidade);
        }

        // // Detalhes
        public ActionResult Detalhes(long id)
        {
            cidades cidade = db.cidades.Find(id);
            return View(cidade);
        }

    }
}

CadeMeuMedico/Views/Cidades/Adicionar.cshtml
@model CadeMeuMedico.Models.cidades
@{
    ViewBag.Title = "Adicionar";
}


@using (Html.BeginForm("Adicionar", "Cidades", FormMethod.Post, new { @class="form-horizontal"})) //Gera o formulario Html
{
    @Html.AntiForgeryToken() //Gera um token de segurança
    @Html.ValidationSummary(true) //Valida as mensagens de segurança
    
    <div class="editor-label"> <!--Cria um Label-->
        <label>Nome</label>
    </div>
    <div class="editor-field"> <!--Cria um campo-->
        @Html.TextBoxFor(model => model.Nome, new { @class="form-control"})
        @Html.ValidationMessageFor(model => model.Nome) <!--Valida os dados desse campo-->
    </div>
    <br />
    <p>
        <input type="submit" value="Adicionar" class="btn btn-primary"/>
    </p>
}
<div>
    @Html.ActionLink("Voltar para a lista de Cidades", "ListaCidades", null, new { @class="btn btn-success"})
</div>
@section script{
    <script>
        $("#menuCidades").addClass("active");
    </script>
}

CadeMeuMedico/Views/Cidades/Editar.cshtml
@model CadeMeuMedico.Models.cidades
@{
    ViewBag.Title = "Editar";
}


@using (Html.BeginForm("Editar", "Cidades", FormMethod.Post, new { @class="form-horizontal"}))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    
    <div class="editor-field">
        @Html.HiddenFor(model => model.IDCidade)
        @Html.ValidationMessageFor(model => model.IDCidade)
    </div>
    <div class="editor-label">
        @Html.LabelFor(model => model.Nome)
    </div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.Nome, new { @class="form-control"})
        @Html.ValidationMessageFor(model => model.Nome)
    </div>
    <br />
    <p>
        <input type="submit" value="Salvar" class="btn btn-primary"/>
    </p>
}
<div>
    @Html.ActionLink("Voltar para a lista de Cidades", "ListaCidades", null, new { @class="btn btn-success"})
</div>
@section script{
    <script>
        $("#menuCidades").addClass("active");
    </script>
}

CadeMeuMedico/Views/Cidades/ListaCidades.cshtml
@model IEnumerable<CadeMeuMedico.Models.cidades>
@{
    ViewBag.Title = "Lista Cidades";
}


<p>@Html.ActionLink("Adicionar Cidade", "Adicionar", null, new { @class="btn btn-primary"})</p>

<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.Nome)</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(model => item.Nome)</td>
            <td>
            @Html.ActionLink("Editar", "Editar", new { id=item.IDCidade}) |
            @Html.ActionLink("Excluir", "Excluir", new {id=item.IDCidade})
            </td>
        </tr>
    }
</table>
@section script{
    <script>
        $("#menuCidades").addClass("active");
    </script>
}