CadeMeuMedico/Controllers/EspecialidadeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CadeMeuMedico.Models;
using System.Data;

namespace CadeMeuMedico.Controllers
{
    public class EspecialidadeController : BaseController
    {
        //
        // GET: /Especialidade/
        private cademeumedicoEntities db = new cademeumedicoEntities();

        public ActionResult ListaEspecialidade()
        {
            var especialidade = db.especialidades.ToList(); // // SELECT
            return View(especialidade);
        }


        // // INSERT
        public ActionResult Adicionar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Adicionar(especialidades especialidade)
        {
            if (ModelState.IsValid)
            {
                db.especialidades.Add(especialidade);
                db.SaveChanges();
                return RedirectToAction("ListaEspecialidade");
            }
            return View(especialidade);
        }

        // // UPDATE
        public ActionResult Editar(long id)
        {
            especialidades especialidade = db.especialidades.Find(id);

            return View(especialidade);
        }

        [HttpPost]
        public ActionResult Editar(especialidades especialidade)
        {
            if (ModelState.IsValid)
            {
                db.Entry(especialidade).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ListaEspecialidade");
            }
            return View(especialidade);
        }

        // // DELETE
        public ActionResult Excluir(long id)
        {
            especialidades especialidade = db.especialidades.Find(id);
            if (especialidade != null)
            {
                db.especialidades.Remove(especialidade);
                db.SaveChanges();
                return RedirectToAction("ListaEspecialidade");
            }
            return View(especialidade);
        }
    }
}

CadeMeuMedico/Controllers/MedicosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CadeMeuMedico.Models;
using System.Data; //Referenciando o Models para ter acesso ao contexto de entidade do EF (Instância do banco)

namespace CadeMeuMedico.Controllers
{
    public class MedicosController : BaseController
    {
       private cademeumedicoEntities db = new cademeumedicoEntities(); //Instância com o banco de dados

        public ActionResult ListaMedicos() // // // SELECT
        {
            var Medico = db.medicos.ToList();
            return View(Medico);
        }


        //  //  //INSERT

        public ActionResult Adicionar() //Pagina do formulario de cadastro de novos medicos
        {//Usando o  ViewBag para transferir dados do controler para as Views, atraves das prop IDCidade e IDEspecialidade
            //Cada uma das prop contem a lista de Cidades e Especialidades, SelectList();
            ViewBag.IDCidade = new SelectList(db.cidades, "IDCidade", "Nome");
            ViewBag.IDEspecialidade = new SelectList(db.especialidades, "IDEspecialidade", "Nome");
            return View();
        }
        [HttpPost] //Action que envia os dados do form ao server
        public ActionResult Adicionar(medicos medico)
        {
            if (ModelState.IsValid) //Chama a validação criada para cada prop das classes criadas como metadados
            {
                db.medicos.Add(medico);
                db.SaveChanges();
                return RedirectToAction("ListaMedicos"); //Retorna para a lista com os medicos cadastrados
            }
            ViewBag.IDCidade = new SelectList(db.cidades, "IDCidade", "Nome", medico.IDCidade);
            ViewBag.IDEspecialidade = new SelectList(db.especialidades, "IDEspecialidade", "Nome", medico.IDEspecialidade);

            return View(medico);
        }


        //  //  //UPDATE

        public ActionResult Editar(long id) //Mostra o form com os dados para serem Editados
        {
            medicos medico = db.medicos.Find(id); //Recupera os dados do medico pelo ID
            ViewBag.IDCidade = new SelectList(db.cidades, "IDCidade", "Nome", medico.IDCidade);
            ViewBag.IDEspecialidade = new SelectList(db.especialidades, "IDEspecialidade", "Nome", medico.IDEspecialidade);

            return View(medico);
        }

        [HttpPost]
        public ActionResult Editar(medicos medico) //Envia os dados alterados ao servidor de destino
        {
            if (ModelState.IsValid)
            {
                db.Entry(medico).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ListaMedicos");
            }

            ViewBag.IDCidade = new SelectList(db.cidades, "IDCidade", "Nome", medico.IDCidade);
            ViewBag.IDEspecialidade = new SelectList(db.especialidades, "IDEspecialidade", "Nome");

            return View(medico);
        }

        //  //  // DELETE
        /*[HttpGet]
        public ActionResult Excluir(long id)
        {
            medicos medico = db.medicos.Find(id);
            if (medico != null)
            {
                db.medicos.Remove(medico);
                db.SaveChanges();
            }
            return RedirectToAction("ListaMedicos");
        }*/
        [HttpGet]
        public string Excluir(long id)
        {
            try
            {
                medicos medico = db.medicos.Find(id);
                db.medicos.Remove(medico);
                db.SaveChanges();
                return Boolean.TrueString;
            }
            catch
            {
                return Boolean.FalseString;
            }
        }
    }
}

CadeMeuMedico/Views/Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="pt-br">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <title>Cadê Meu Medico - @ViewBag.Title</title> <!--ViewBag Mostra na view valores predefinidos, nesse caso mostra o titulo da pag-->
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet"/>
    <!--O Url.Content converte um diretorio virtual relativo para um diretorio absoluto na aplicação-->
     
   <!--<link href="~/styles" rel="stylesheet"/> <!--Aumenta o desempenho caso tenha muitos arquivos para serem referenciados
                                               dessa forma em vez de ser feita varias requisições ao servidor, apenas uma é 
                                               feita, pois o framework verifica todos os arquivos dentro do diretorio, combina
                                               e minifica os arquivos devolvendo uma resposta HTTP de um unico arquivo CSS    
                                               -->
    <style>
        body{padding-top:60px;}.navbar-header .navbar-brand{color:#ff6a00;font-weight:bold;text-transform:uppercase;text-shadow:10px 5px 6px #ff0000;}
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="~/">Cadê Meu Medico?</a>&nbsp; &nbsp;
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                   <!--<li class="active"><a href="~/">Home</a></li>-->
                    <!--Cria um link com o href em tempo de execução-->
                    <li id="menuMedicos">@Html.ActionLink("Médicos","ListaMedicos", "Medicos")</li>
                    <li id="menuCidades">@Html.ActionLink("Cidades","ListaCidades","Cidades")</li>
                    <li id="menuEspecialidade">@Html.ActionLink("Especialidades", "ListaEspecialidade", "Especialidade")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        @RenderBody() <!--Usado para renderizar as view, ou seja, sendo assim todas as view vão usar esse Layout-->
    </div>
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("script",required:false) <!--Sessão onde os scripts serão renderizados-->
</body>
</html>